sudo: required
services:
  - docker

before_install:
  - docker build -t chansd5/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chansd5/react-test npm test

deploy:
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-719222167959"
  bucket_path: "docker-multi"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

after_success:
  - docker build -t chansd5/multi-client ./client
  - docker build -t chansd5/multi-nginx ./nginx
  - docker build -t chansd5/multi-server ./server
  - docker build -t chansd5/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push chansd5/multi-client
  - docker push chansd5/multi-nginx
  - docker push chansd5/multi-server
  - docker push chansd5/multi-worker


